root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/discord-bot"
  cmd = "make"
  delay = 500
  exclude_dir = ["assets", "bin", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = false
