// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Team-bluekunVRC/discord-bot/ent/discorduser"
	"github.com/Team-bluekunVRC/discord-bot/ent/user"
	"github.com/Team-bluekunVRC/discord-bot/ent/vrcuser"
	"github.com/google/uuid"
)

// DiscordUserCreate is the builder for creating a DiscordUser entity.
type DiscordUserCreate struct {
	config
	mutation *DiscordUserMutation
	hooks    []Hook
}

// SetID sets the "id" field.
func (duc *DiscordUserCreate) SetID(s string) *DiscordUserCreate {
	duc.mutation.SetID(s)
	return duc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (duc *DiscordUserCreate) AddUserIDs(ids ...uuid.UUID) *DiscordUserCreate {
	duc.mutation.AddUserIDs(ids...)
	return duc
}

// AddUser adds the "user" edges to the User entity.
func (duc *DiscordUserCreate) AddUser(u ...*User) *DiscordUserCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duc.AddUserIDs(ids...)
}

// AddVrcIDs adds the "vrc" edge to the VRCUser entity by IDs.
func (duc *DiscordUserCreate) AddVrcIDs(ids ...string) *DiscordUserCreate {
	duc.mutation.AddVrcIDs(ids...)
	return duc
}

// AddVrc adds the "vrc" edges to the VRCUser entity.
func (duc *DiscordUserCreate) AddVrc(v ...*VRCUser) *DiscordUserCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return duc.AddVrcIDs(ids...)
}

// Mutation returns the DiscordUserMutation object of the builder.
func (duc *DiscordUserCreate) Mutation() *DiscordUserMutation {
	return duc.mutation
}

// Save creates the DiscordUser in the database.
func (duc *DiscordUserCreate) Save(ctx context.Context) (*DiscordUser, error) {
	var (
		err  error
		node *DiscordUser
	)
	if len(duc.hooks) == 0 {
		if err = duc.check(); err != nil {
			return nil, err
		}
		node, err = duc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiscordUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = duc.check(); err != nil {
				return nil, err
			}
			duc.mutation = mutation
			if node, err = duc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(duc.hooks) - 1; i >= 0; i-- {
			if duc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (duc *DiscordUserCreate) SaveX(ctx context.Context) *DiscordUser {
	v, err := duc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (duc *DiscordUserCreate) Exec(ctx context.Context) error {
	_, err := duc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duc *DiscordUserCreate) ExecX(ctx context.Context) {
	if err := duc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duc *DiscordUserCreate) check() error {
	if v, ok := duc.mutation.ID(); ok {
		if err := discorduser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "id": %w`, err)}
		}
	}
	if len(duc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New("ent: missing required edge \"user\"")}
	}
	if len(duc.mutation.VrcIDs()) == 0 {
		return &ValidationError{Name: "vrc", err: errors.New("ent: missing required edge \"vrc\"")}
	}
	return nil
}

func (duc *DiscordUserCreate) sqlSave(ctx context.Context) (*DiscordUser, error) {
	_node, _spec := duc.createSpec()
	if err := sqlgraph.CreateNode(ctx, duc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(string)
	}
	return _node, nil
}

func (duc *DiscordUserCreate) createSpec() (*DiscordUser, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscordUser{config: duc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: discorduser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: discorduser.FieldID,
			},
		}
	)
	if id, ok := duc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := duc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.UserTable,
			Columns: []string{discorduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := duc.mutation.VrcIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   discorduser.VrcTable,
			Columns: []string{discorduser.VrcColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: vrcuser.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiscordUserCreateBulk is the builder for creating many DiscordUser entities in bulk.
type DiscordUserCreateBulk struct {
	config
	builders []*DiscordUserCreate
}

// Save creates the DiscordUser entities in the database.
func (ducb *DiscordUserCreateBulk) Save(ctx context.Context) ([]*DiscordUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ducb.builders))
	nodes := make([]*DiscordUser, len(ducb.builders))
	mutators := make([]Mutator, len(ducb.builders))
	for i := range ducb.builders {
		func(i int, root context.Context) {
			builder := ducb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscordUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ducb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ducb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ducb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ducb *DiscordUserCreateBulk) SaveX(ctx context.Context) []*DiscordUser {
	v, err := ducb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ducb *DiscordUserCreateBulk) Exec(ctx context.Context) error {
	_, err := ducb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ducb *DiscordUserCreateBulk) ExecX(ctx context.Context) {
	if err := ducb.Exec(ctx); err != nil {
		panic(err)
	}
}
