// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Team-bluekunVRC/discord-bot/ent/discorduser"
	"github.com/Team-bluekunVRC/discord-bot/ent/predicate"
)

// DiscordUserDelete is the builder for deleting a DiscordUser entity.
type DiscordUserDelete struct {
	config
	hooks    []Hook
	mutation *DiscordUserMutation
}

// Where appends a list predicates to the DiscordUserDelete builder.
func (dud *DiscordUserDelete) Where(ps ...predicate.DiscordUser) *DiscordUserDelete {
	dud.mutation.Where(ps...)
	return dud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dud *DiscordUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dud.hooks) == 0 {
		affected, err = dud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiscordUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dud.mutation = mutation
			affected, err = dud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dud.hooks) - 1; i >= 0; i-- {
			if dud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dud *DiscordUserDelete) ExecX(ctx context.Context) int {
	n, err := dud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dud *DiscordUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: discorduser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: discorduser.FieldID,
			},
		},
	}
	if ps := dud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dud.driver, _spec)
}

// DiscordUserDeleteOne is the builder for deleting a single DiscordUser entity.
type DiscordUserDeleteOne struct {
	dud *DiscordUserDelete
}

// Exec executes the deletion query.
func (dudo *DiscordUserDeleteOne) Exec(ctx context.Context) error {
	n, err := dudo.dud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discorduser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dudo *DiscordUserDeleteOne) ExecX(ctx context.Context) {
	dudo.dud.ExecX(ctx)
}
