// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Team-bluekunVRC/discord-bot/ent/discorduser"
	"github.com/Team-bluekunVRC/discord-bot/ent/predicate"
	"github.com/Team-bluekunVRC/discord-bot/ent/user"
	"github.com/Team-bluekunVRC/discord-bot/ent/vrcuser"
	"github.com/google/uuid"
)

// VRCUserQuery is the builder for querying VRCUser entities.
type VRCUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.VRCUser
	// eager-loading edges.
	withUser    *UserQuery
	withDiscord *DiscordUserQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VRCUserQuery builder.
func (vuq *VRCUserQuery) Where(ps ...predicate.VRCUser) *VRCUserQuery {
	vuq.predicates = append(vuq.predicates, ps...)
	return vuq
}

// Limit adds a limit step to the query.
func (vuq *VRCUserQuery) Limit(limit int) *VRCUserQuery {
	vuq.limit = &limit
	return vuq
}

// Offset adds an offset step to the query.
func (vuq *VRCUserQuery) Offset(offset int) *VRCUserQuery {
	vuq.offset = &offset
	return vuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vuq *VRCUserQuery) Unique(unique bool) *VRCUserQuery {
	vuq.unique = &unique
	return vuq
}

// Order adds an order step to the query.
func (vuq *VRCUserQuery) Order(o ...OrderFunc) *VRCUserQuery {
	vuq.order = append(vuq.order, o...)
	return vuq
}

// QueryUser chains the current query on the "user" edge.
func (vuq *VRCUserQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: vuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vrcuser.Table, vrcuser.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, vrcuser.UserTable, vrcuser.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(vuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDiscord chains the current query on the "discord" edge.
func (vuq *VRCUserQuery) QueryDiscord() *DiscordUserQuery {
	query := &DiscordUserQuery{config: vuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vrcuser.Table, vrcuser.FieldID, selector),
			sqlgraph.To(discorduser.Table, discorduser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, vrcuser.DiscordTable, vrcuser.DiscordColumn),
		)
		fromU = sqlgraph.SetNeighbors(vuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VRCUser entity from the query.
// Returns a *NotFoundError when no VRCUser was found.
func (vuq *VRCUserQuery) First(ctx context.Context) (*VRCUser, error) {
	nodes, err := vuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vrcuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vuq *VRCUserQuery) FirstX(ctx context.Context) *VRCUser {
	node, err := vuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VRCUser ID from the query.
// Returns a *NotFoundError when no VRCUser ID was found.
func (vuq *VRCUserQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = vuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vrcuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vuq *VRCUserQuery) FirstIDX(ctx context.Context) string {
	id, err := vuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VRCUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one VRCUser entity is not found.
// Returns a *NotFoundError when no VRCUser entities are found.
func (vuq *VRCUserQuery) Only(ctx context.Context) (*VRCUser, error) {
	nodes, err := vuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vrcuser.Label}
	default:
		return nil, &NotSingularError{vrcuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vuq *VRCUserQuery) OnlyX(ctx context.Context) *VRCUser {
	node, err := vuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VRCUser ID in the query.
// Returns a *NotSingularError when exactly one VRCUser ID is not found.
// Returns a *NotFoundError when no entities are found.
func (vuq *VRCUserQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = vuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = &NotSingularError{vrcuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vuq *VRCUserQuery) OnlyIDX(ctx context.Context) string {
	id, err := vuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VRCUsers.
func (vuq *VRCUserQuery) All(ctx context.Context) ([]*VRCUser, error) {
	if err := vuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vuq *VRCUserQuery) AllX(ctx context.Context) []*VRCUser {
	nodes, err := vuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VRCUser IDs.
func (vuq *VRCUserQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := vuq.Select(vrcuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vuq *VRCUserQuery) IDsX(ctx context.Context) []string {
	ids, err := vuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vuq *VRCUserQuery) Count(ctx context.Context) (int, error) {
	if err := vuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vuq *VRCUserQuery) CountX(ctx context.Context) int {
	count, err := vuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vuq *VRCUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := vuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vuq *VRCUserQuery) ExistX(ctx context.Context) bool {
	exist, err := vuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VRCUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vuq *VRCUserQuery) Clone() *VRCUserQuery {
	if vuq == nil {
		return nil
	}
	return &VRCUserQuery{
		config:      vuq.config,
		limit:       vuq.limit,
		offset:      vuq.offset,
		order:       append([]OrderFunc{}, vuq.order...),
		predicates:  append([]predicate.VRCUser{}, vuq.predicates...),
		withUser:    vuq.withUser.Clone(),
		withDiscord: vuq.withDiscord.Clone(),
		// clone intermediate query.
		sql:  vuq.sql.Clone(),
		path: vuq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (vuq *VRCUserQuery) WithUser(opts ...func(*UserQuery)) *VRCUserQuery {
	query := &UserQuery{config: vuq.config}
	for _, opt := range opts {
		opt(query)
	}
	vuq.withUser = query
	return vuq
}

// WithDiscord tells the query-builder to eager-load the nodes that are connected to
// the "discord" edge. The optional arguments are used to configure the query builder of the edge.
func (vuq *VRCUserQuery) WithDiscord(opts ...func(*DiscordUserQuery)) *VRCUserQuery {
	query := &DiscordUserQuery{config: vuq.config}
	for _, opt := range opts {
		opt(query)
	}
	vuq.withDiscord = query
	return vuq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (vuq *VRCUserQuery) GroupBy(field string, fields ...string) *VRCUserGroupBy {
	group := &VRCUserGroupBy{config: vuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (vuq *VRCUserQuery) Select(fields ...string) *VRCUserSelect {
	vuq.fields = append(vuq.fields, fields...)
	return &VRCUserSelect{VRCUserQuery: vuq}
}

func (vuq *VRCUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vuq.fields {
		if !vrcuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vuq.path != nil {
		prev, err := vuq.path(ctx)
		if err != nil {
			return err
		}
		vuq.sql = prev
	}
	return nil
}

func (vuq *VRCUserQuery) sqlAll(ctx context.Context) ([]*VRCUser, error) {
	var (
		nodes       = []*VRCUser{}
		withFKs     = vuq.withFKs
		_spec       = vuq.querySpec()
		loadedTypes = [2]bool{
			vuq.withUser != nil,
			vuq.withDiscord != nil,
		}
	)
	if vuq.withUser != nil || vuq.withDiscord != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, vrcuser.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &VRCUser{config: vuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, vuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := vuq.withUser; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*VRCUser)
		for i := range nodes {
			if nodes[i].vrc_user_user == nil {
				continue
			}
			fk := *nodes[i].vrc_user_user
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "vrc_user_user" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	if query := vuq.withDiscord; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*VRCUser)
		for i := range nodes {
			if nodes[i].discord_user_vrc == nil {
				continue
			}
			fk := *nodes[i].discord_user_vrc
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(discorduser.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "discord_user_vrc" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Discord = n
			}
		}
	}

	return nodes, nil
}

func (vuq *VRCUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vuq.querySpec()
	return sqlgraph.CountNodes(ctx, vuq.driver, _spec)
}

func (vuq *VRCUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := vuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (vuq *VRCUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   vrcuser.Table,
			Columns: vrcuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: vrcuser.FieldID,
			},
		},
		From:   vuq.sql,
		Unique: true,
	}
	if unique := vuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vrcuser.FieldID)
		for i := range fields {
			if fields[i] != vrcuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vuq *VRCUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vuq.driver.Dialect())
	t1 := builder.Table(vrcuser.Table)
	columns := vuq.fields
	if len(columns) == 0 {
		columns = vrcuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vuq.sql != nil {
		selector = vuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range vuq.predicates {
		p(selector)
	}
	for _, p := range vuq.order {
		p(selector)
	}
	if offset := vuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VRCUserGroupBy is the group-by builder for VRCUser entities.
type VRCUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vugb *VRCUserGroupBy) Aggregate(fns ...AggregateFunc) *VRCUserGroupBy {
	vugb.fns = append(vugb.fns, fns...)
	return vugb
}

// Scan applies the group-by query and scans the result into the given value.
func (vugb *VRCUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := vugb.path(ctx)
	if err != nil {
		return err
	}
	vugb.sql = query
	return vugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vugb *VRCUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := vugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(vugb.fields) > 1 {
		return nil, errors.New("ent: VRCUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := vugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vugb *VRCUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := vugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vugb *VRCUserGroupBy) StringX(ctx context.Context) string {
	v, err := vugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(vugb.fields) > 1 {
		return nil, errors.New("ent: VRCUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := vugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vugb *VRCUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := vugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vugb *VRCUserGroupBy) IntX(ctx context.Context) int {
	v, err := vugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(vugb.fields) > 1 {
		return nil, errors.New("ent: VRCUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := vugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vugb *VRCUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := vugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vugb *VRCUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := vugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(vugb.fields) > 1 {
		return nil, errors.New("ent: VRCUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := vugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vugb *VRCUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := vugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vugb *VRCUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vugb *VRCUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := vugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vugb *VRCUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range vugb.fields {
		if !vrcuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vugb *VRCUserGroupBy) sqlQuery() *sql.Selector {
	selector := vugb.sql.Select()
	aggregation := make([]string, 0, len(vugb.fns))
	for _, fn := range vugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(vugb.fields)+len(vugb.fns))
		for _, f := range vugb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(vugb.fields...)...)
}

// VRCUserSelect is the builder for selecting fields of VRCUser entities.
type VRCUserSelect struct {
	*VRCUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (vus *VRCUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := vus.prepareQuery(ctx); err != nil {
		return err
	}
	vus.sql = vus.VRCUserQuery.sqlQuery(ctx)
	return vus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vus *VRCUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := vus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(vus.fields) > 1 {
		return nil, errors.New("ent: VRCUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := vus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vus *VRCUserSelect) StringsX(ctx context.Context) []string {
	v, err := vus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vus *VRCUserSelect) StringX(ctx context.Context) string {
	v, err := vus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(vus.fields) > 1 {
		return nil, errors.New("ent: VRCUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := vus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vus *VRCUserSelect) IntsX(ctx context.Context) []int {
	v, err := vus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vus *VRCUserSelect) IntX(ctx context.Context) int {
	v, err := vus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(vus.fields) > 1 {
		return nil, errors.New("ent: VRCUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := vus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vus *VRCUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := vus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vus *VRCUserSelect) Float64X(ctx context.Context) float64 {
	v, err := vus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(vus.fields) > 1 {
		return nil, errors.New("ent: VRCUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := vus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vus *VRCUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := vus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (vus *VRCUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vrcuser.Label}
	default:
		err = fmt.Errorf("ent: VRCUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vus *VRCUserSelect) BoolX(ctx context.Context) bool {
	v, err := vus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vus *VRCUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := vus.sql.Query()
	if err := vus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
