// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AudioClip is the predicate function for audioclip builders.
type AudioClip func(*sql.Selector)

// DiscordUser is the predicate function for discorduser builders.
type DiscordUser func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VRCUser is the predicate function for vrcuser builders.
type VRCUser func(*sql.Selector)
